### PR TITLE
training done for one variable. Model can save.

### PR DESCRIPTION
**Pull request by ikeborei**
There's not many comments but i tried my best to make variables clear. Also no tests written yet. Right now, I can save the trained model but i kept getting an error when I try to retrieve it.

### CODE REVIEW

**Comment by shawnhugginsjr** [comment]
Can you add the tensor flow module to the requirements file. Also, what error are you getting when you try to retrieve the model?

**Comment by ikeborei** [comment]
Added tensor flow to requirements. 
can now retrieve model. Still have to finetune some things. But we can get a count

**Comment by shawnhugginsjr** [comment]
Nice, the last thing would just be reading from the actual csv feature file. If you still can't generate the file yourself, I can send you example data.

**Comment by ikeborei** [comment]
I actually added a dataset.csv file which I read from. The values are from batch2 images. I processed them to get the front count but added the full counts manually. Just incase you wanted to run it on your computer to see how it performs. I used a comma delimiter just so its easier to view in excel.

**Comment by ikeborei** [comment]
I'll work on generating the actual csv file.

**Comment by shawnhugginsjr** [comment]
You also updated the config, correct? The Sample config will also have to be updated.

Also, I've noticed that you're using np.getfromtxt to get your datapoint. That's fine, but the current feature file format is this ['image filename', 'front facing kernel count'], which probably doesn't match the expected input. We can always remove 'image filename', but the final kernel count still wouldn't be included in the feature file. Before the training starts, we're probably going to have to run a function that for each image places all of its feature data (no filename) and final kernel count in a row in dataset.csv.

**Comment by shawnhugginsjr** [comment]
Looks good to me.

**Comment by tylernielson1** [comment]
I think it looks good too.

**Pull request merged**
